#!/bin/sh
#
# DFF -- An open source Digital Forensics Framework.
#
# Copyright (C) 2009 ArxSys
#
# Malinge Christophe <christophe.malinge@arxsys.fr>
#
# See http://www.digital-forensic.org for more information about
# this project. Please do not directly contact
# any of the maintainers of this project for assistance;
# the project provides a web site, mailing lists and IRC
# channels for your use.
#
# This program is free software, distributed under the terms of
# the GNU General Public License Version 3. See the LICENSE file
# at the top of the source tree.
#
#
# This script starts DFF. Its right place is in /usr/bin or
# /usr/local/bin (installer does it).
# It sets library path in order libraries from the DFF API be
# well resolved.
# 

LD_LIBRARY_PATH=/usr/lib/python2.6/site-packages/api/exceptions:/usr/lib/python2.6/site-packages/api/env:/usr/lib/python2.6/site-packages/api/loader:/usr/lib/python2.6/site-packages/api/module:/usr/lib/python2.6/site-packages/api/vfs:/usr/lib/python2.6/site-packages/api/type:/usr/lib/python2.6/site-packages/api/magic python /usr/lib/python2.6/site-packages/dff/dff.py $*
